# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Gnome2-Wnck
version:      0.13
version_from: Wnck.pm
installdirs:  site
requires:
    ExtUtils::Depends:             0.20
    ExtUtils::PkgConfig:           1.03
    Glib:                          1.04
    Gtk2:                          1.00

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
