--- #YAML:1.0
name:                Gnome2-Wnck
version:             0.15
abstract:            Perl interface to the Window Navigator Construction Kit
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.38
distribution_type:   module
requires:     
    ExtUtils::Depends:             0.20
    ExtUtils::PkgConfig:           1.03
    Glib:                          1.04
    Gtk2:                          1.00
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
